Repository brstu/OTIS-2022, pull requests merged in 2022-12, with the labels that each got.

#42 lab2
  trunk/ii02116/task02/doc/Lab2.md
  trunk/ii02116/task02/src/Lab2.jl
Labels: duplicate

#56 LAB3
  trunk/ii02105/task_03/doc/1.png
  trunk/ii02105/task_03/doc/2.png
  trunk/ii02105/task_03/doc/3.png
  trunk/ii02105/task_03/doc/4.png
  trunk/ii02105/task_03/doc/5.png
  trunk/ii02105/task_03/doc/report.md
  trunk/ii02105/task_03/src/G1.txt
  trunk/ii02105/task_03/src/G3.pkl
  trunk/ii02105/task_03/src/alg_button_lib.py
  trunk/ii02105/task_03/src/demo.ipynb
  trunk/ii02105/task_03/src/export.py
  trunk/ii02105/task_03/src/lib.py
Labels: question

#55 lab3
  trunk/ii02108/task_03/doc/images/1.png
  trunk/ii02108/task_03/doc/images/10.png
  trunk/ii02108/task_03/doc/images/11.png
  trunk/ii02108/task_03/doc/images/12.png
  trunk/ii02108/task_03/doc/images/13.png
  trunk/ii02108/task_03/doc/images/2.png
  trunk/ii02108/task_03/doc/images/3.png
  trunk/ii02108/task_03/doc/images/4.png
  trunk/ii02108/task_03/doc/images/5.png
  trunk/ii02108/task_03/doc/images/6.png
  trunk/ii02108/task_03/doc/images/7.png
  trunk/ii02108/task_03/doc/images/8.png
  trunk/ii02108/task_03/doc/images/9.png
  trunk/ii02108/task_03/doc/readme.md
  trunk/ii02108/task_03/src/Examples/Example.txt
  trunk/ii02108/task_03/src/Examples/example.graph
  trunk/ii02108/task_03/src/Examples/test_eulerian.graph
  trunk/ii02108/task_03/src/Examples/test_eulerian2.graph
  trunk/ii02108/task_03/src/config.py
  trunk/ii02108/task_03/src/graphs.py
  trunk/ii02108/task_03/src/icons/icon_for_close_tab.png
  trunk/ii02108/task_03/src/icons/icon_for_newgraph.png
  trunk/ii02108/task_03/src/main.py
  trunk/ii02108/task_03/src/main_components.py
Labels: good first issue, question

#57 lab3
  trunk/ii02107/task_03/doc/images/1.png
  trunk/ii02107/task_03/doc/images/2.png
  trunk/ii02107/task_03/doc/images/3.png
  trunk/ii02107/task_03/doc/images/5.png
  trunk/ii02107/task_03/doc/images/6.png
  trunk/ii02107/task_03/doc/images/7.png
  trunk/ii02107/task_03/doc/readme.md
  trunk/ii02107/task_03/src/info.txt
  trunk/ii02107/task_03/src/main.py
Labels: question

#59 Lab3
  trunk/ii02206/task_03/doc/interface.png
  trunk/ii02206/task_03/doc/readme.md
  trunk/ii02206/task_03/src/color_wheel.png
  trunk/ii02206/task_03/src/graphs.pde
Labels: question
