Repository brstu/OTIS-2022, pull requests merged in 2023-01, with the labels that each got.

#83 lab4
  trunk/ii02108/task_04/doc/images/img.png
  trunk/ii02108/task_04/doc/images/img2.png
  trunk/ii02108/task_04/doc/readme.md
Labels: good first issue, question

#94 Lab №4
  trunk/ii02104/task_04/doc/1.png
  trunk/ii02104/task_04/doc/2.png
  trunk/ii02104/task_04/doc/7.png
  trunk/ii02104/task_04/doc/readme.md
Labels: good first issue, question

#97 Lab №3
  trunk/ii02104/task_03/doc/readme.md
  trunk/ii02104/task_03/src/ab.txt
  trunk/ii02104/task_03/src/example.csv
  trunk/ii02104/task_03/src/main.py
Labels: question

#142 Lab5
  trunk/II02111/task_05/doc/images/1.png
  trunk/II02111/task_05/doc/images/2.png
  trunk/II02111/task_05/doc/readme.md
Labels: ii22

#144 Lab5
  trunk/ii02115/task_05/doc/readme.md
Labels: question
